/*
    Намеренно без #pragma once: это список #undef для завершения летописного
    участка. После него можно вновь писать обычный C++ в том же translation unit.

    Повторно включить drevnerus.hpp в этом же файле уже не получится из-за
    #pragma once, поэтому включайте отмену только в самом конце такого участка.
*/

#undef аще
#undef ащели
#undef инако
#undef дондеже
#undef деяти
#undef длявсякаго
#undef избрати
#undef случай
#undef обычно
#undef возврати
#undef прервати
#undef продолжити
#undef истинно
#undef ложно
#undef да
#undef несть
#undef ничтоже
#undef начати
#undef окончати
#undef пусто
#undef цело
#undef кратко
#undef долго
#undef предолго
#undef беззнака
#undef сознаком
#undef дробно
#undef великодробно
#undef буква
#undef широкабуква
#undef истина
#undef натурально
#undef само
#undef постоянно
#undef неизменно
#undef неподвижно
#undef внешне
#undef изменяемо
#undef явно
#undef встроено
#undef летуче
#undef безвозвратно
#undef безбедно
#undef именослов
#undef употреби
#undef псевдоним
#undef образец
#undef род
#undef сословие
#undef устроение
#undef единение
#undef перечень
#undef переченьсословие
#undef открыто
#undef сокровенно
#undef защищено
#undef другъ
#undef мнимо
#undef превозмочь
#undef окончательно
#undef сие
#undef ново
#undef сотворити
#undef погубити
#undef размеръ
#undef ровнение
#undef разновидность
#undef явнообрати
#undef динамичнообрати
#undef неизменнообрати
#undef грубообрати
#undef попытай
#undef улови
#undef возверзи
#undef и
#undef или
#undef не
#undef равно
#undef неравно
#undef боле
#undef мене
#undef немене
#undef неболе
#undef имать
#undef прибавити
#undef отъяти
#undef умножити
#undef разделити
#undef побитово_и
#undef побитово_или
#undef побитово_либо
#undef побитово_не
#undef главныйъ
#undef строка
#undef видстроки
#undef векторъ
#undef массивъ
#undef списокъ
#undef очередьдвустороння
#undef очередь
#undef стопа
#undef словарь
#undef быстрословарь
#undef множество
#undef быстромножество
#undef единовластный
#undef общий
#undef слабый
#undef сотворитиединого
#undef сотворитиобщего
#undef возможно
#undef нетзначения
#undef разновидно
#undef двигати
#undef препровождати
#undef поменяти
#undef глаголи
#undef возгласи
#undef внемли
#undef конецстроки

#undef количество
#undef пустоли
#undef вместимость
#undef очистити
#undef зарезервировати
#undef ужати
#undef начальныйходок
#undef конечныйходок
#undef обратныйначальныйходок
#undef обратныйконечныйходок
#undef добавити
#undef добавитисначала
#undef добавитивконец
#undef удалитьпервое
#undef удалитьпоследнее
#undef вставити
#undef изъяти
#undef по_месту
#undef по_месту_вконец
#undef передний
#undef задний
#undef данные
#undef приписати
#undef подстрока
#undef длина
#undef найти
#undef сколько
#undef перво
#undef второ
#undef естьзначение
#undef извлечь
#undef илизначение
#undef номеррода
#undef получить
#undef сбросити
#undef освободити
#undef счетссылок
#undef единственноли
#undef истеклоли
#undef заперти
#undef упорядочити
#undef отыскати
#undef всяколи
#undef хотькто
#undef никто
#undef сосчитати
#undef надвсяким
#undef обратити
#undef убратьесли

